
rem Start Kafka

set KAFKA_NAME=kafka
set KAFKA_ZOOKEEPER_CONNECT=localhost:32181
set KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29092
set KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
set IMAGE=confluentinc/cp-kafka:5.4.1
:set IMAGE=confluentinc/cp-kafka:latest

docker run -d --net=host --name=%KAFKA_NAME% -e KAFKA_ZOOKEEPER_CONNECT=%KAFKA_ZOOKEEPER_CONNECT% -e KAFKA_ADVERTISED_LISTENERS=%KAFKA_ADVERTISED_LISTENERS% -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=%KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR% %IMAGE%
